// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqtmetpfpqaaakdysggo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xdG1ldHBmcHFhYWFrZHlzZ2dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTQ4OTQsImV4cCI6MjA1OTYzMDg5NH0.JXOzu0wZBc2xH9eb6l4SLUDilvDDSI72shP596PK0IE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);